# Generated by Django 2.1.1 on 2018-11-01 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('para1', models.CharField(max_length=200)),
                ('para2', models.CharField(max_length=200)),
                ('para3', models.CharField(max_length=200)),
                ('para4', models.CharField(max_length=200)),
                ('para5', models.CharField(max_length=200)),
                ('para6', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PoolMux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='miner.Miner')),
                ('pool', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='miner.Pool')),
            ],
        ),
    ]
