# Generated by Django 2.1.1 on 2018-11-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miner', '0011_miner_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='miner',
            name='pool',
            field=models.ManyToManyField(through='miner.PoolMux', to='miner.Pool'),
        ),
    ]
